version: "2"
services:
  db:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "3004:27017"
  
  models:
    image: "node:8"
    user: "node"
    environment:
      - NODE_ENV=production
    links:
      - db:db
    volumes:
      - ./models:/app
    ports:
    - "3001:8000"
    command: >
          bash -c "cd ./app
          && npm install
          && npm start"

  exp:
    image: "node:8"
    user: "node"
    environment:
      - NODE_ENV=production
    links:
      - models:models-api
    volumes:
      - ./experience:/app
    ports:
    - "3002:8000"
    command: >
          bash -c "cd ./app
          && npm install
          && npm start"

  frontend:
    image: "node:8"
    user: "node"
    environment:
      - NODE_ENV=production
    links:
      - exp:exp-api
    volumes:
      - ./frontend:/app
    ports:
    - "3003:3000"
    command: >
          bash -c "cd ./app
          && npm install
          && npm start"
